build:
 version: "3.0"
cards:
 message: "welcome to cards configuration"
 contactDetails:
  name: "Nikita Nagaraj"
  email: "cse_cards@gmial.com"
 onCallSupport:
  - "(555)555-1234"
  - "(555)555-3456"   
      
   
  
  