build:
 version: "4.0"
loans:
 message: "welcome to loans web hook docker prod environment"
 contactDetails:
  name: "Nagaraju_loans_prod"
  email: "cse_loans_prod@gmail.com"
 onCallSupport:
  - (555)555-1234
  - (555)555-3456 
